[icon-theme]
name = "Nomo Dark"

[icon-theme.ui]

"file" = "src/file.svg"
"directory.closed" = "src/folder.close.svg"
"directory.opened" = "src/folder.open.svg"

[icon-theme.foldername]

".vscode" = "src/folder.vs.close.svg"
".git" = "src/folder.git.close.svg"
"spec" = "src/folder.test.close.svg"
"test" = "src/folder.test.close.svg"
"tests" = "src/folder.test.close.svg"
"__tests__" = "src/folder.test.close.svg"
"node_modules" = "src/folder.js.close.svg"
"build" = "src/folder.dist.close.svg"
"bin" = "src/folder.dist.close.svg"
".bin" = "src/folder.dist.close.svg"
"dist" = "src/folder.dist.close.svg"
"deploy" = "src/folder.dist.close.svg"
"src" = "src/folder.src.close.svg"
"include" = "src/folder.include.close.svg"
"source" = "src/folder.src.close.svg"
"lib" = "src/folder.lib.close.svg"
"typings" = "src/folder.ts.close.svg"
"types" = "src/folder.ts.close.svg"
"dev" = "src/folder.dev.close.svg"
"prod" = "src/folder.prod.close.svg"
"api" = "src/folder.api.close.svg"
"events" = "src/folder.events.close.svg"
".github" = "src/folder.github.close.svg"
"data" = "src/folder.data.close.svg"

[icon-theme.filename]

"package.json" = "src/config.npm.svg"
".npmignore" = "src/config.npm.svg"
".npmrc" = "src/config.npm.svg"
".esformatter" = "src/config.format.svg"
".clang-format" = "src/config.format.svg"
".tfignore" = "src/config.vs.svg"
".vscodeignore" = "src/config.vs.svg"
".gitignore" = "src/config.git.svg"
".gitattributes" = "src/config.git.svg"
".travis.yml" = "src/config.travis.svg"
"appveyor.yml" = "src/config.appveyor.svg"
"licence" = "src/config.license.svg"
"license" = "src/config.license.svg"
"licence.md" = "src/config.license.svg"
"license.md" = "src/config.license.svg"
"copying" = "src/config.license.svg"
".editorconfig" = "src/config.editorconfig.svg"
"readme.md" = "src/file.markdown.svg"
"makefile" = "src/config.makefile.svg"
"readme" = "src/file.text.svg"
"install" = "src/file.text.svg"
"releases" = "src/file.text.svg"
".bowerrc" = "src/config.bower.svg"
"bower.json" = "src/config.bower.svg"
"dockerfile" = "src/config.docker.svg"
"test.dockerfile" = "src/config.docker.test.svg"
"gruntfile" = "src/config.grunt.svg"
"gruntfile.js" = "src/config.grunt.svg"
"gulpfile" = "src/config.gulp.svg"
"gulpfile.js" = "src/config.gulp.svg"
"gulpfile.babel.js" = "src/config.gulp.svg"
".eslintrc" = "src/config.eslint.svg"
".eslintrc.js" = "src/config.eslint.svg"
".eslintrc.json" = "src/config.eslint.svg"
".eslintrc.yaml" = "src/config.eslint.svg"
".eslintrc.yml" = "src/config.eslint.svg"
".eslintignore" = "src/config.eslint.svg"
".babelrc" = "src/config.babel.svg"
"yarn.lock" = "src/config.yarn.svg"
".env" = "src/file.env.svg"

[icon-theme.extension]

"tf" = "src/file.tf.svg"
"json" = "src/file.json.svg"
"c" = "src/file.c.svg"
"h" = "src/file.h.svg"
"hpp" = "src/file.h.svg"
"hxx" = "src/file.h.svg"
"hh" = "src/file.h.svg"
"cpp" = "src/file.cpp.svg"
"cc" = "src/file.cpp.svg"
"cxx" = "src/file.cpp.svg"
"d" = "src/file.d.svg"
"di" = "src/file.d.svg"
"js" = "src/file.js.svg"
"mjs" = "src/file.js.svg"
"jshintrc" = "src/file.js.svg"
"html" = "src/file.html.svg"
"htm" = "src/file.html.svg"
"css" = "src/file.css.svg"
"styl" = "src/file.stylus.svg"
"sass" = "src/file.sass.svg"
"scss" = "src/file.sass.svg"
"less" = "src/file.less.svg"
"md" = "src/file.markdown.svg"
"cs" = "src/file.cs.svg"
"fs" = "src/file.fs.svg"
"go" = "src/file.go.svg"
"lua" = "src/file.lua.svg"
"rs" = "src/file.rust.svg"
"py" = "src/file.python.svg"
"ruo" = "src/file.ruota.svg"
"rb" = "src/file.ruby.svg"
"jl" = "src/file.julia.svg"
"php" = "src/file.php.svg"
"haxe" = "src/file.haxe.svg"
"hxml" = "src/file.haxe.svg"
"java" = "src/file.java.svg"
"ts" = "src/file.ts.svg"
"d.ts" = "src/file.d.ts.svg"
"vue" = "src/file.vue.svg"
"xml" = "src/file.xml.svg"
"coffee" = "src/file.coffee.svg"
"litcoffee" = "src/file.coffee.svg"
"ex" = "src/file.elixir.svg"
"exs" = "src/file.elixir.svg"
"clj" = "src/file.clojure.svg"
"jsx" = "src/file.jsx.svg"
"gql" = "src/file.gql.svg"
"tsx" = "src/file.tsx.svg"
"toml" = "src/file.toml.svg"
"yml" = "src/file.yaml.svg"
"yaml" = "src/file.yaml.svg"
"ss" = "src/file.scheme.svg"
"scm" = "src/file.scheme.svg"
"lisp" = "src/file.lisp.svg"
"lsp" = "src/file.lisp.svg"
"l" = "src/file.lisp.svg"
"cl" = "src/file.lisp.svg"
"fasl" = "src/file.lisp.svg"
"el" = "src/file.elisp.svg"
"elc" = "src/file.elisp.svg"
"ptl" = "src/file.ptl.svg"
"patel" = "src/file.ptl.svg"
"hs" = "src/file.haskell.svg"
"lhs" = "src/file.haskell.svg"
"idr" = "src/file.idris.svg"
"v" = "src/file.coq.svg"
"ml" = "src/file.ml.svg"
"mli" = "src/file.ml.svg"
"mll" = "src/file.ml.svg"
"fst" = "src/file.fst.svg"
"sats" = "src/file.ats.svg"
"dats" = "src/file.ats.svg"
"pro" = "src/file.prolog.svg"
"P" = "src/file.prolog.svg"
"elm" = "src/file.elm.svg"
"purs" = "src/file.purescript.svg"
"slim" = "src/file.slim.svg"
"skim" = "src/file.slim.svg"
"erl" = "src/file.erlang.svg"
"swift" = "src/file.swift.svg"
"tex" = "src/file.tex.svg"
"vb" = "src/file.vb.svg"
"mk" = "src/config.makefile.svg"
"make" = "src/config.makefile.svg"
"jade" = "src/file.jade.svg"
"pug" = "src/file.jade.svg"
"scala" = "src/file.scala.svg"
"js.map" = "src/file.sourcemap.svg"
"css.map" = "src/file.sourcemap.svg"
"sh" = "src/file.shell.svg"
"zsh" = "src/file.shell.svg"
"bash" = "src/file.shell.svg"
"fish" = "src/file.shell.svg"
"elv" = "src/file.shell.svg"
"bat" = "src/file.shell.svg"
"cmd" = "src/file.shell.svg"
"txt" = "src/file.text.svg"
"bmp" = "src/file.image.svg"
"jpg" = "src/file.image.svg"
"jpeg" = "src/file.image.svg"
"gif" = "src/file.image.svg"
"png" = "src/file.image.svg"
"svg" = "src/file.image.svg"
"tif" = "src/file.image.svg"
"tiff" = "src/file.image.svg"
"psd" = "src/file.image.svg"
"psb" = "src/file.image.svg"
"ttf" = "src/file.font.svg"
"otf" = "src/file.font.svg"
"woff" = "src/file.font.svg"
"woff2" = "src/file.font.svg"
"sfd" = "src/file.font.svg"
"eot" = "src/file.font.svg"
"otd" = "src/file.json.svg"
"exe" = "src/file.exe.svg"
"dll" = "src/file.lib.svg"
"lib" = "src/file.lib.svg"
"a" = "src/file.lib.svg"
"so" = "src/file.lib.svg"
"zip" = "src/file.zip.svg"
"tar" = "src/file.zip.svg"
"tgz" = "src/file.zip.svg"
"gz" = "src/file.zip.svg"
"xz" = "src/file.zip.svg"
"bzip2" = "src/file.zip.svg"
"7z" = "src/file.zip.svg"
"rar" = "src/file.zip.svg"
"hbs" = "src/file.handlebars.svg"
"ps1" = "src/file.powershell.svg"
"tests.ps1" = "src/file.pester.svg"
"test.ps1" = "src/file.pester.svg"
"cer" = "src/file.crt.svg"
"cert" = "src/file.crt.svg"
"crt" = "src/file.crt.svg"
"der" = "src/file.crt.svg"
"key" = "src/file.key.svg"
"pem" = "src/file.crt.svg"
"cr" = "src/file.cr.svg"
"ecr" = "src/file.cr.svg"
"env" = "src/file.env.svg"
