name = "nomo-dark-icons"
version = "1.0.0"
display-name = "Nomo Dark Icons"
author = "netroxen"
description = "Nomo Dark icon theme for Lapce"
icon = "assets/logo.png"
repository = "Netroxen/nomo-dark-lapce"
icon-themes = ["nomo.toml"]
